=== Baransarinalbant/1ME323lab/L1/filmer.dtd
<!--
superheromovies
    movie
        name
            caption
        when
            year
        length
            minutes
        description
            attr: url
        imdb
            points
-->

<!ELEMENT superheromovies (movie+)>
    <!ELEMENT movie (name, when, length, description, imdb)>
        <!ELEMENT name (caption)>
            <!ELEMENT caption (#PCDATA)>
        <!ELEMENT when (year)>
            <!ELEMENT year (#PCDATA)>
        <!ELEMENT length (minutes)>
            <!ELEMENT minutes (#PCDATA)>
        <!ELEMENT description EMPTY>
            <!ATTLIST description url CDATA #REQUIRED>
        <!ELEMENT imdb (points)>
            <!ELEMENT points (#PCDATA)>

=== Baransarinalbant/1ME323lab/L1/others.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE superheromovies SYSTEM "filmer.dtd"> 
   
<superheromovies>

    <movie>
        <name>Hellboy</name>
        <when>2019</when>
        <length>2h</length>
        <imdb url="https://www.imdb.com/title/tt2274648/?ref_=nv_sr_srsg_3" />
    </movie>

    <movie>
        <name>The Incredibles</name>
        <when>2004</when>
        <length>1h 55m</length>
        <imdb url="https://www.imdb.com/title/tt0317705/?ref_=nv_sr_srsg_3"/>
    </movie>

    <movie>
        <name>Teenage Mutant Ninja Turtles</name>
        <when>2014</when>
        <length>1h 41m</length>
        <imdb url="https://www.imdb.com/title/tt1291150/?ref_=nv_sr_srsg_6" />
    </movie>

    <movie>
        <name>Dredd</name>
        <when>2012</when>
        <length>1h 35m</length>
        <imdb url="https://www.imdb.com/title/tt1343727/?ref_=nv_sr_srsg_0" />
    </movie>

</superheromovies>

=== Baransarinalbant/1ME323lab/L1/dc.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE superheromovies SYSTEM "filmer.dtd"> 
   
<superheromovies>

    <movie>
        <name>
            <caption>Joker</caption>
        </name>
        <when>
            <year>2019</year>
        </when>
        <length>
            <minutes>2h 2m</minutes>
        </length>
        <description url="https://www.imdb.com/title/tt7286456/?ref_=nv_sr_srsg_0" />
        <imdb>
            <points>8,4/10</points>
        </imdb>
    </movie>

    <movie>
        <name>
            <caption>Wonder Woman 1984</caption>
        </name>
        <when>
            <year>2020</year>
        </when>
        <length>
            <minutes>2h 31m</minutes>
        </length>
        <description url="https://www.imdb.com/title/tt7126948/?ref_=nv_sr_srsg_0" />
        <imdb>
            <points>5,4/10</points>
        </imdb>
    </movie>

    <movie>
        <name>
            <caption>Batman v Superman: Dawn of Justice</caption>
        </name>
        <when>
            <year>2016</year>
        </when>
        <length>
            <minutes>2h 32m</minutes>
        </length>
        <description url="https://www.imdb.com/title/tt2975590/?ref_=nv_sr_srsg_0" />
        <imdb>
            <points>6,4/10</points>
        </imdb>
    </movie>

    <movie>
        <name>
            <caption>The Suicide Squad</caption>
        </name>
        <when>
            <year>2021</year>
        </when>
        <length>
            <minutes>2h 12m</minutes>
        </length>
        <description url="https://www.imdb.com/title/tt6334354/?ref_=nv_sr_srsg_0" />
        <imdb>
            <points>7,2/10</points>
        </imdb>
    </movie>

</superheromovies>

=== Baransarinalbant/1ME323lab/L1/marvel.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE superheromovies SYSTEM "filmer.dtd"> 
   
<superheromovies>

    <movie>
        <name>Spiderman: No Way Home</name>
        <when>2021</when>
        <length>2h 28m</length>
        <imdb url="https://www.imdb.com/title/tt10872600/" />
    </movie>

    <movie>
        <name>Doctor Strange</name>
        <when>2016</when>
        <length>1h 55m</length>
        <imdb url="https://www.imdb.com/title/tt1211837/?ref_=fn_al_tt_1" />
    </movie>

    <movie>
        <name>Captain America: The First Avenger</name>
        <when>2011</when>
        <length>2h 4m</length>
        <imdb url="https://www.imdb.com/title/tt0458339/?ref_=fn_al_tt_3" />
    </movie>

    <movie>
        <name>Thor</name>
        <when>2011</when>
        <length>1h 55m</length>
        <imdb url="https://www.imdb.com/title/tt0800369/?ref_=fn_al_tt_1" />
    </movie>

</superheromovies>
